### ISSUE TITLE
Stack deployment fails upon selecting 'Create ChangeSet'

### ISSUE THREAD

**Issue by gamebusterz** [awslabs/amazon-s3-find-and-forget#224] opened 2020-11-27 12:26 UTC
**Version**: Latest as on 27 Nov 2020

While trying deploy the Cloudformation template for [S3F2](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=S3F2&templateURL=https://solution-builders-us-east-1.s3.us-east-1.amazonaws.com/amazon-s3-find-and-forget/latest/template.yaml), following all the default steps, when I select **Create ChangeSet** (as per step 7 in the [instructions](https://github.com/awslabs/amazon-s3-find-and-forget/blob/master/docs/USER_GUIDE.md#deploying-the-solution)), the **ChangeSet** fails at the `APIStack` stage, with the following error :   

`Nested change set arn:aws:cloudformation:region:account_id:changeSet/S3F2-random-APIStack-random was not successfully created: Currently in FAILED` 

This causes all the other `S3F2` stacks to be stuck in **Review in Progress** state
![Screenshot 2020-11-27 at 3 40 18 PM](https://user-images.githubusercontent.com/6880188/100448867-fbc51b00-30d8-11eb-8d6d-2a9313674f61.png)

----

On the other hand, following the exact same steps but selecting 'Create Stack' in the last step:
![Screenshot 2020-11-27 at 5 53 14 PM](https://user-images.githubusercontent.com/6880188/100449175-79892680-30d9-11eb-89ef-46b520920527.png)

This leads to everything getting created without any problems and the solution is ready to be used after few minutes. 
![Screenshot 2020-11-27 at 4 03 37 PM](https://user-images.githubusercontent.com/6880188/100449290-ab9a8880-30d9-11eb-90e7-590b67ee140e.png)

----

Please note this only observed while deploying the solution template, not the IAM Role template.

**Comment by matteofigus** [comment] 2020-11-27 12:43
I can reproduce. In the API Stack changeset, I see `Usage of {{IntrinsicFunction:S3F2Changeset/AuthStack.Outputs.CognitoUserPoolArn/Fn::GetAtt}} is not allowed.`

**Comment by matteofigus** [comment] 2021-05-20 10:47
For now we have no resolution in place, the only supported method is deploying without Changeset. I think this is caused by an underlining bug in SAM or CloudFormation

**Comment by matteofigus** [comment] 2022-12-19 18:11
This bug has been fixed by downstream services and I cannot reproduce anymore. Deploying by creating the ChangeSet first succeeds without errors.

**Closed by matteofigus** 2022-12-19 18:11 UTC
Labels: bug
